"""empty message

Revision ID: 00da55b484ea
Revises: 7d2f668ea81d
Create Date: 2022-08-03 14:15:11.998536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00da55b484ea'
down_revision = '7d2f668ea81d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('livro', sa.String(length=255), nullable=True),
    sa.Column('escritor', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bood')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bood',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('livro', sa.VARCHAR(length=255), nullable=True),
    sa.Column('escritor', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('book')
    # ### end Alembic commands ###
